### ISSUE TITLE
KeyError on sequence_number

### ISSUE THREAD

**Issue by MarianoAkaMery** [ackness/aptc#1]
"sequence_number": str(client.get_account_sequence_number(account_address)),
KeyError
'sequence_number'

**Comment by ackness** [comment]
Hi, in my test, client.get_account_sequence_number(address), it works fine, can you give me more information about this error?

<img width="550" alt="image" src="https://user-images.githubusercontent.com/19150500/197778537-512af34f-5cbd-4ea0-8b08-3eedd0d47f1e.png">
<img width="527" alt="image" src="https://user-images.githubusercontent.com/19150500/197778572-bc0a6711-ed10-4a8b-a89a-918bf18dcf5c.png">

**Comment by MarianoAkaMery** [comment]
I think is now working, can you tell me how you send and address as argument?
I know I need to serialize it as struct, but how to import it
![image](https://user-images.githubusercontent.com/42919644/197810887-8bbb2add-6167-4c7f-a2d8-e663cf19844f.png)

**Comment by ackness** [comment]
It seems your struct is correct, maybe this transaction need to input type_arguments.
maybe your should check the functions and modules parameters.

**Comment by MarianoAkaMery** [comment]
Is possible to talk with you on discord ?

**Comment by ackness** [comment]
sry, I don't use discord, you can send your question to my email. ackness8@gmail.com
